### ISSUE TITLE
Slack招待が来ません 

### ISSUE THREAD

**Issue by tao524** [progedu/commands#1]
リンクされたフォームから申請して20分ほど経ちますが、招待メールが届きません。
問題が起きていないか、ご確認いただけないでしょうか？

**Comment by iuyghasf897** [comment]
私も同様にリンクされたフォームから申請したのですが、招待メールが届きませんでした。
迷惑メールとしてブロックされているようでもなさそうなので、一度ご確認いただくことは可能でしょうか。
もし対応方法に誤りがありましたら、申し訳ありません。

**Comment by hirosaki** [comment]
同様です。リンク集からクリックしてメールアドレスを入力しても、本から打ち込んでメールアドレスを入力しても招待メールが届きません。
よろしくおねがいします。

**Comment by ohataken** [comment]
おお、ご迷惑おかけしております。

実は、しばらく前に [ここ](https://progedu.slack.com/join/shared_invite/enQtMzk4OTU4NTU0NDM3LTI0NzU1MzE5NmYwYjAzNDMyYTlkNmJlOGMwMWM0M2ZkN2NiMWNiMjQxYTkyNjNjY2IzODYyNjgwNDI4ZGIzNzQ) から自分でSlackのWorkspaceに入れるようになりました。なので、こちらから入っていただけますか？

おそらく、このリポジトリのread.meからGoogle フォームを辿られたかと思うので、そちらを消すようにします。

**Comment by hirosaki** [comment]
ありがとうございました。
入ることができました。

hirosaki

2019年2月14日(木) 11:08 Ken Ohata <notifications@github.com>:

**Comment by tao524** [comment]
入ることができました。ありがとうございました。
